<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: animal_facility.proto

namespace Proto\AnimalFacilityService;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Responses
 *
 * Generated from protobuf message <code>AnimalFacilityServicePackage.GetAnimalFacilitiesResponse</code>
 */
class GetAnimalFacilitiesResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .AnimalFacilityServicePackage.TemplateAnimalFacility animal_facilities = 1;</code>
     */
    private $animal_facilities;
    /**
     * Generated from protobuf field <code>int32 response_code = 2;</code>
     */
    protected $response_code = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Proto\AnimalFacilityService\TemplateAnimalFacility>|\Google\Protobuf\Internal\RepeatedField $animal_facilities
     *     @type int $response_code
     * }
     */
    public function __construct($data = NULL) {
        \Proto\Metadata\AnimalFacility::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .AnimalFacilityServicePackage.TemplateAnimalFacility animal_facilities = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAnimalFacilities()
    {
        return $this->animal_facilities;
    }

    /**
     * Generated from protobuf field <code>repeated .AnimalFacilityServicePackage.TemplateAnimalFacility animal_facilities = 1;</code>
     * @param array<\Proto\AnimalFacilityService\TemplateAnimalFacility>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAnimalFacilities($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Proto\AnimalFacilityService\TemplateAnimalFacility::class);
        $this->animal_facilities = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 response_code = 2;</code>
     * @return int
     */
    public function getResponseCode()
    {
        return $this->response_code;
    }

    /**
     * Generated from protobuf field <code>int32 response_code = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setResponseCode($var)
    {
        GPBUtil::checkInt32($var);
        $this->response_code = $var;

        return $this;
    }

}

