<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: animal_facility.proto

namespace Proto\AnimalFacilityService;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>AnimalFacilityServicePackage.TemplateAnimal</code>
 */
class TemplateAnimal extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional int32 id = 1;</code>
     */
    protected $id = null;
    /**
     * Generated from protobuf field <code>optional bool is_consignment_approved = 2;</code>
     */
    protected $is_consignment_approved = null;
    /**
     * Generated from protobuf field <code>optional int32 species_id = 3;</code>
     */
    protected $species_id = null;
    /**
     * Generated from protobuf field <code>int32 breed_id = 4;</code>
     */
    protected $breed_id = 0;
    /**
     * Generated from protobuf field <code>optional int32 age = 5;</code>
     */
    protected $age = null;
    /**
     * Generated from protobuf field <code>optional string description = 6;</code>
     */
    protected $description = null;
    /**
     * Generated from protobuf field <code>string status = 7;</code>
     */
    protected $status = '';
    /**
     * Generated from protobuf field <code>int32 country_id = 8;</code>
     */
    protected $country_id = 0;
    /**
     * Generated from protobuf field <code>int32 facility_id = 9;</code>
     */
    protected $facility_id = 0;
    /**
     * Generated from protobuf field <code>string registration_type = 10;</code>
     */
    protected $registration_type = '';
    /**
     * Generated from protobuf field <code>int32 owner_id = 11;</code>
     */
    protected $owner_id = 0;
    /**
     * Generated from protobuf field <code>string identification = 12;</code>
     */
    protected $identification = '';
    /**
     * Generated from protobuf field <code>optional int32 number_of_males = 13;</code>
     */
    protected $number_of_males = null;
    /**
     * Generated from protobuf field <code>optional int32 number_of_females = 14;</code>
     */
    protected $number_of_females = null;
    /**
     * Generated from protobuf field <code>optional int32 total_number = 15;</code>
     */
    protected $total_number = null;
    /**
     * Generated from protobuf field <code>bool is_exotic = 16;</code>
     */
    protected $is_exotic = false;
    /**
     * Generated from protobuf field <code>optional int32 weqaa_record_id = 17;</code>
     */
    protected $weqaa_record_id = null;
    /**
     * Generated from protobuf field <code>optional string sex = 18;</code>
     */
    protected $sex = null;
    /**
     * Generated from protobuf field <code>optional string remarks = 19;</code>
     */
    protected $remarks = null;
    /**
     * Generated from protobuf field <code>optional int32 province_id = 20;</code>
     */
    protected $province_id = null;
    /**
     * Generated from protobuf field <code>optional string area = 21;</code>
     */
    protected $area = null;
    /**
     * Generated from protobuf field <code>optional string nickname = 22;</code>
     */
    protected $nickname = null;
    /**
     * Generated from protobuf field <code>optional string scientific_name = 23;</code>
     */
    protected $scientific_name = null;
    /**
     * Generated from protobuf field <code>optional string rfid = 24;</code>
     */
    protected $rfid = null;
    /**
     * Generated from protobuf field <code>optional string branding = 25;</code>
     */
    protected $branding = null;
    /**
     * Generated from protobuf field <code>optional string ear_tag = 26;</code>
     */
    protected $ear_tag = null;
    /**
     * Generated from protobuf field <code>optional string microchip = 27;</code>
     */
    protected $microchip = null;
    /**
     * Generated from protobuf field <code>optional string pedigree = 28;</code>
     */
    protected $pedigree = null;
    /**
     * Generated from protobuf field <code>optional string unit = 29;</code>
     */
    protected $unit = null;
    /**
     * Generated from protobuf field <code>optional int32 unit_value = 30;</code>
     */
    protected $unit_value = null;
    /**
     * Generated from protobuf field <code>optional int32 service_id = 31;</code>
     */
    protected $service_id = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $id
     *     @type bool $is_consignment_approved
     *     @type int $species_id
     *     @type int $breed_id
     *     @type int $age
     *     @type string $description
     *     @type string $status
     *     @type int $country_id
     *     @type int $facility_id
     *     @type string $registration_type
     *     @type int $owner_id
     *     @type string $identification
     *     @type int $number_of_males
     *     @type int $number_of_females
     *     @type int $total_number
     *     @type bool $is_exotic
     *     @type int $weqaa_record_id
     *     @type string $sex
     *     @type string $remarks
     *     @type int $province_id
     *     @type string $area
     *     @type string $nickname
     *     @type string $scientific_name
     *     @type string $rfid
     *     @type string $branding
     *     @type string $ear_tag
     *     @type string $microchip
     *     @type string $pedigree
     *     @type string $unit
     *     @type int $unit_value
     *     @type int $service_id
     * }
     */
    public function __construct($data = NULL) {
        \Proto\Metadata\AnimalFacility::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional int32 id = 1;</code>
     * @return int
     */
    public function getId()
    {
        return isset($this->id) ? $this->id : 0;
    }

    public function hasId()
    {
        return isset($this->id);
    }

    public function clearId()
    {
        unset($this->id);
    }

    /**
     * Generated from protobuf field <code>optional int32 id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt32($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool is_consignment_approved = 2;</code>
     * @return bool
     */
    public function getIsConsignmentApproved()
    {
        return isset($this->is_consignment_approved) ? $this->is_consignment_approved : false;
    }

    public function hasIsConsignmentApproved()
    {
        return isset($this->is_consignment_approved);
    }

    public function clearIsConsignmentApproved()
    {
        unset($this->is_consignment_approved);
    }

    /**
     * Generated from protobuf field <code>optional bool is_consignment_approved = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsConsignmentApproved($var)
    {
        GPBUtil::checkBool($var);
        $this->is_consignment_approved = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int32 species_id = 3;</code>
     * @return int
     */
    public function getSpeciesId()
    {
        return isset($this->species_id) ? $this->species_id : 0;
    }

    public function hasSpeciesId()
    {
        return isset($this->species_id);
    }

    public function clearSpeciesId()
    {
        unset($this->species_id);
    }

    /**
     * Generated from protobuf field <code>optional int32 species_id = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setSpeciesId($var)
    {
        GPBUtil::checkInt32($var);
        $this->species_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 breed_id = 4;</code>
     * @return int
     */
    public function getBreedId()
    {
        return $this->breed_id;
    }

    /**
     * Generated from protobuf field <code>int32 breed_id = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setBreedId($var)
    {
        GPBUtil::checkInt32($var);
        $this->breed_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int32 age = 5;</code>
     * @return int
     */
    public function getAge()
    {
        return isset($this->age) ? $this->age : 0;
    }

    public function hasAge()
    {
        return isset($this->age);
    }

    public function clearAge()
    {
        unset($this->age);
    }

    /**
     * Generated from protobuf field <code>optional int32 age = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setAge($var)
    {
        GPBUtil::checkInt32($var);
        $this->age = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string description = 6;</code>
     * @return string
     */
    public function getDescription()
    {
        return isset($this->description) ? $this->description : '';
    }

    public function hasDescription()
    {
        return isset($this->description);
    }

    public function clearDescription()
    {
        unset($this->description);
    }

    /**
     * Generated from protobuf field <code>optional string description = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string status = 7;</code>
     * @return string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>string status = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkString($var, True);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 country_id = 8;</code>
     * @return int
     */
    public function getCountryId()
    {
        return $this->country_id;
    }

    /**
     * Generated from protobuf field <code>int32 country_id = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setCountryId($var)
    {
        GPBUtil::checkInt32($var);
        $this->country_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 facility_id = 9;</code>
     * @return int
     */
    public function getFacilityId()
    {
        return $this->facility_id;
    }

    /**
     * Generated from protobuf field <code>int32 facility_id = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setFacilityId($var)
    {
        GPBUtil::checkInt32($var);
        $this->facility_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string registration_type = 10;</code>
     * @return string
     */
    public function getRegistrationType()
    {
        return $this->registration_type;
    }

    /**
     * Generated from protobuf field <code>string registration_type = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setRegistrationType($var)
    {
        GPBUtil::checkString($var, True);
        $this->registration_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 owner_id = 11;</code>
     * @return int
     */
    public function getOwnerId()
    {
        return $this->owner_id;
    }

    /**
     * Generated from protobuf field <code>int32 owner_id = 11;</code>
     * @param int $var
     * @return $this
     */
    public function setOwnerId($var)
    {
        GPBUtil::checkInt32($var);
        $this->owner_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string identification = 12;</code>
     * @return string
     */
    public function getIdentification()
    {
        return $this->identification;
    }

    /**
     * Generated from protobuf field <code>string identification = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setIdentification($var)
    {
        GPBUtil::checkString($var, True);
        $this->identification = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int32 number_of_males = 13;</code>
     * @return int
     */
    public function getNumberOfMales()
    {
        return isset($this->number_of_males) ? $this->number_of_males : 0;
    }

    public function hasNumberOfMales()
    {
        return isset($this->number_of_males);
    }

    public function clearNumberOfMales()
    {
        unset($this->number_of_males);
    }

    /**
     * Generated from protobuf field <code>optional int32 number_of_males = 13;</code>
     * @param int $var
     * @return $this
     */
    public function setNumberOfMales($var)
    {
        GPBUtil::checkInt32($var);
        $this->number_of_males = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int32 number_of_females = 14;</code>
     * @return int
     */
    public function getNumberOfFemales()
    {
        return isset($this->number_of_females) ? $this->number_of_females : 0;
    }

    public function hasNumberOfFemales()
    {
        return isset($this->number_of_females);
    }

    public function clearNumberOfFemales()
    {
        unset($this->number_of_females);
    }

    /**
     * Generated from protobuf field <code>optional int32 number_of_females = 14;</code>
     * @param int $var
     * @return $this
     */
    public function setNumberOfFemales($var)
    {
        GPBUtil::checkInt32($var);
        $this->number_of_females = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int32 total_number = 15;</code>
     * @return int
     */
    public function getTotalNumber()
    {
        return isset($this->total_number) ? $this->total_number : 0;
    }

    public function hasTotalNumber()
    {
        return isset($this->total_number);
    }

    public function clearTotalNumber()
    {
        unset($this->total_number);
    }

    /**
     * Generated from protobuf field <code>optional int32 total_number = 15;</code>
     * @param int $var
     * @return $this
     */
    public function setTotalNumber($var)
    {
        GPBUtil::checkInt32($var);
        $this->total_number = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_exotic = 16;</code>
     * @return bool
     */
    public function getIsExotic()
    {
        return $this->is_exotic;
    }

    /**
     * Generated from protobuf field <code>bool is_exotic = 16;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsExotic($var)
    {
        GPBUtil::checkBool($var);
        $this->is_exotic = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int32 weqaa_record_id = 17;</code>
     * @return int
     */
    public function getWeqaaRecordId()
    {
        return isset($this->weqaa_record_id) ? $this->weqaa_record_id : 0;
    }

    public function hasWeqaaRecordId()
    {
        return isset($this->weqaa_record_id);
    }

    public function clearWeqaaRecordId()
    {
        unset($this->weqaa_record_id);
    }

    /**
     * Generated from protobuf field <code>optional int32 weqaa_record_id = 17;</code>
     * @param int $var
     * @return $this
     */
    public function setWeqaaRecordId($var)
    {
        GPBUtil::checkInt32($var);
        $this->weqaa_record_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string sex = 18;</code>
     * @return string
     */
    public function getSex()
    {
        return isset($this->sex) ? $this->sex : '';
    }

    public function hasSex()
    {
        return isset($this->sex);
    }

    public function clearSex()
    {
        unset($this->sex);
    }

    /**
     * Generated from protobuf field <code>optional string sex = 18;</code>
     * @param string $var
     * @return $this
     */
    public function setSex($var)
    {
        GPBUtil::checkString($var, True);
        $this->sex = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string remarks = 19;</code>
     * @return string
     */
    public function getRemarks()
    {
        return isset($this->remarks) ? $this->remarks : '';
    }

    public function hasRemarks()
    {
        return isset($this->remarks);
    }

    public function clearRemarks()
    {
        unset($this->remarks);
    }

    /**
     * Generated from protobuf field <code>optional string remarks = 19;</code>
     * @param string $var
     * @return $this
     */
    public function setRemarks($var)
    {
        GPBUtil::checkString($var, True);
        $this->remarks = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int32 province_id = 20;</code>
     * @return int
     */
    public function getProvinceId()
    {
        return isset($this->province_id) ? $this->province_id : 0;
    }

    public function hasProvinceId()
    {
        return isset($this->province_id);
    }

    public function clearProvinceId()
    {
        unset($this->province_id);
    }

    /**
     * Generated from protobuf field <code>optional int32 province_id = 20;</code>
     * @param int $var
     * @return $this
     */
    public function setProvinceId($var)
    {
        GPBUtil::checkInt32($var);
        $this->province_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string area = 21;</code>
     * @return string
     */
    public function getArea()
    {
        return isset($this->area) ? $this->area : '';
    }

    public function hasArea()
    {
        return isset($this->area);
    }

    public function clearArea()
    {
        unset($this->area);
    }

    /**
     * Generated from protobuf field <code>optional string area = 21;</code>
     * @param string $var
     * @return $this
     */
    public function setArea($var)
    {
        GPBUtil::checkString($var, True);
        $this->area = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string nickname = 22;</code>
     * @return string
     */
    public function getNickname()
    {
        return isset($this->nickname) ? $this->nickname : '';
    }

    public function hasNickname()
    {
        return isset($this->nickname);
    }

    public function clearNickname()
    {
        unset($this->nickname);
    }

    /**
     * Generated from protobuf field <code>optional string nickname = 22;</code>
     * @param string $var
     * @return $this
     */
    public function setNickname($var)
    {
        GPBUtil::checkString($var, True);
        $this->nickname = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string scientific_name = 23;</code>
     * @return string
     */
    public function getScientificName()
    {
        return isset($this->scientific_name) ? $this->scientific_name : '';
    }

    public function hasScientificName()
    {
        return isset($this->scientific_name);
    }

    public function clearScientificName()
    {
        unset($this->scientific_name);
    }

    /**
     * Generated from protobuf field <code>optional string scientific_name = 23;</code>
     * @param string $var
     * @return $this
     */
    public function setScientificName($var)
    {
        GPBUtil::checkString($var, True);
        $this->scientific_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string rfid = 24;</code>
     * @return string
     */
    public function getRfid()
    {
        return isset($this->rfid) ? $this->rfid : '';
    }

    public function hasRfid()
    {
        return isset($this->rfid);
    }

    public function clearRfid()
    {
        unset($this->rfid);
    }

    /**
     * Generated from protobuf field <code>optional string rfid = 24;</code>
     * @param string $var
     * @return $this
     */
    public function setRfid($var)
    {
        GPBUtil::checkString($var, True);
        $this->rfid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string branding = 25;</code>
     * @return string
     */
    public function getBranding()
    {
        return isset($this->branding) ? $this->branding : '';
    }

    public function hasBranding()
    {
        return isset($this->branding);
    }

    public function clearBranding()
    {
        unset($this->branding);
    }

    /**
     * Generated from protobuf field <code>optional string branding = 25;</code>
     * @param string $var
     * @return $this
     */
    public function setBranding($var)
    {
        GPBUtil::checkString($var, True);
        $this->branding = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string ear_tag = 26;</code>
     * @return string
     */
    public function getEarTag()
    {
        return isset($this->ear_tag) ? $this->ear_tag : '';
    }

    public function hasEarTag()
    {
        return isset($this->ear_tag);
    }

    public function clearEarTag()
    {
        unset($this->ear_tag);
    }

    /**
     * Generated from protobuf field <code>optional string ear_tag = 26;</code>
     * @param string $var
     * @return $this
     */
    public function setEarTag($var)
    {
        GPBUtil::checkString($var, True);
        $this->ear_tag = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string microchip = 27;</code>
     * @return string
     */
    public function getMicrochip()
    {
        return isset($this->microchip) ? $this->microchip : '';
    }

    public function hasMicrochip()
    {
        return isset($this->microchip);
    }

    public function clearMicrochip()
    {
        unset($this->microchip);
    }

    /**
     * Generated from protobuf field <code>optional string microchip = 27;</code>
     * @param string $var
     * @return $this
     */
    public function setMicrochip($var)
    {
        GPBUtil::checkString($var, True);
        $this->microchip = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string pedigree = 28;</code>
     * @return string
     */
    public function getPedigree()
    {
        return isset($this->pedigree) ? $this->pedigree : '';
    }

    public function hasPedigree()
    {
        return isset($this->pedigree);
    }

    public function clearPedigree()
    {
        unset($this->pedigree);
    }

    /**
     * Generated from protobuf field <code>optional string pedigree = 28;</code>
     * @param string $var
     * @return $this
     */
    public function setPedigree($var)
    {
        GPBUtil::checkString($var, True);
        $this->pedigree = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string unit = 29;</code>
     * @return string
     */
    public function getUnit()
    {
        return isset($this->unit) ? $this->unit : '';
    }

    public function hasUnit()
    {
        return isset($this->unit);
    }

    public function clearUnit()
    {
        unset($this->unit);
    }

    /**
     * Generated from protobuf field <code>optional string unit = 29;</code>
     * @param string $var
     * @return $this
     */
    public function setUnit($var)
    {
        GPBUtil::checkString($var, True);
        $this->unit = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int32 unit_value = 30;</code>
     * @return int
     */
    public function getUnitValue()
    {
        return isset($this->unit_value) ? $this->unit_value : 0;
    }

    public function hasUnitValue()
    {
        return isset($this->unit_value);
    }

    public function clearUnitValue()
    {
        unset($this->unit_value);
    }

    /**
     * Generated from protobuf field <code>optional int32 unit_value = 30;</code>
     * @param int $var
     * @return $this
     */
    public function setUnitValue($var)
    {
        GPBUtil::checkInt32($var);
        $this->unit_value = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int32 service_id = 31;</code>
     * @return int
     */
    public function getServiceId()
    {
        return isset($this->service_id) ? $this->service_id : 0;
    }

    public function hasServiceId()
    {
        return isset($this->service_id);
    }

    public function clearServiceId()
    {
        unset($this->service_id);
    }

    /**
     * Generated from protobuf field <code>optional int32 service_id = 31;</code>
     * @param int $var
     * @return $this
     */
    public function setServiceId($var)
    {
        GPBUtil::checkInt32($var);
        $this->service_id = $var;

        return $this;
    }

}

