<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: animal_facility.proto

namespace Proto\AnimalFacilityService;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * AnimalFacility message
 *
 * Generated from protobuf message <code>AnimalFacilityServicePackage.TemplateAnimalFacility</code>
 */
class TemplateAnimalFacility extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional int32 id = 1;</code>
     */
    protected $id = null;
    /**
     * Generated from protobuf field <code>int32 animal_id = 2;</code>
     */
    protected $animal_id = 0;
    /**
     * Generated from protobuf field <code>int32 facility_id = 3;</code>
     */
    protected $facility_id = 0;
    /**
     * Generated from protobuf field <code>.AnimalFacilityServicePackage.TemplateAnimal animal = 4;</code>
     */
    protected $animal = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $id
     *     @type int $animal_id
     *     @type int $facility_id
     *     @type \Proto\AnimalFacilityService\TemplateAnimal $animal
     * }
     */
    public function __construct($data = NULL) {
        \Proto\Metadata\AnimalFacility::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional int32 id = 1;</code>
     * @return int
     */
    public function getId()
    {
        return isset($this->id) ? $this->id : 0;
    }

    public function hasId()
    {
        return isset($this->id);
    }

    public function clearId()
    {
        unset($this->id);
    }

    /**
     * Generated from protobuf field <code>optional int32 id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt32($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 animal_id = 2;</code>
     * @return int
     */
    public function getAnimalId()
    {
        return $this->animal_id;
    }

    /**
     * Generated from protobuf field <code>int32 animal_id = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setAnimalId($var)
    {
        GPBUtil::checkInt32($var);
        $this->animal_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 facility_id = 3;</code>
     * @return int
     */
    public function getFacilityId()
    {
        return $this->facility_id;
    }

    /**
     * Generated from protobuf field <code>int32 facility_id = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setFacilityId($var)
    {
        GPBUtil::checkInt32($var);
        $this->facility_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.AnimalFacilityServicePackage.TemplateAnimal animal = 4;</code>
     * @return \Proto\AnimalFacilityService\TemplateAnimal|null
     */
    public function getAnimal()
    {
        return $this->animal;
    }

    public function hasAnimal()
    {
        return isset($this->animal);
    }

    public function clearAnimal()
    {
        unset($this->animal);
    }

    /**
     * Generated from protobuf field <code>.AnimalFacilityServicePackage.TemplateAnimal animal = 4;</code>
     * @param \Proto\AnimalFacilityService\TemplateAnimal $var
     * @return $this
     */
    public function setAnimal($var)
    {
        GPBUtil::checkMessage($var, \Proto\AnimalFacilityService\TemplateAnimal::class);
        $this->animal = $var;

        return $this;
    }

}

