<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: animal_facility.proto

namespace Proto\AnimalFacilityService;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>AnimalFacilityServicePackage.UpdateAnimalFacilityResponse</code>
 */
class UpdateAnimalFacilityResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.AnimalFacilityServicePackage.TemplateAnimalFacility animal_facility = 1;</code>
     */
    protected $animal_facility = null;
    /**
     * Generated from protobuf field <code>int32 response_code = 2;</code>
     */
    protected $response_code = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Proto\AnimalFacilityService\TemplateAnimalFacility $animal_facility
     *     @type int $response_code
     * }
     */
    public function __construct($data = NULL) {
        \Proto\Metadata\AnimalFacility::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.AnimalFacilityServicePackage.TemplateAnimalFacility animal_facility = 1;</code>
     * @return \Proto\AnimalFacilityService\TemplateAnimalFacility|null
     */
    public function getAnimalFacility()
    {
        return $this->animal_facility;
    }

    public function hasAnimalFacility()
    {
        return isset($this->animal_facility);
    }

    public function clearAnimalFacility()
    {
        unset($this->animal_facility);
    }

    /**
     * Generated from protobuf field <code>.AnimalFacilityServicePackage.TemplateAnimalFacility animal_facility = 1;</code>
     * @param \Proto\AnimalFacilityService\TemplateAnimalFacility $var
     * @return $this
     */
    public function setAnimalFacility($var)
    {
        GPBUtil::checkMessage($var, \Proto\AnimalFacilityService\TemplateAnimalFacility::class);
        $this->animal_facility = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 response_code = 2;</code>
     * @return int
     */
    public function getResponseCode()
    {
        return $this->response_code;
    }

    /**
     * Generated from protobuf field <code>int32 response_code = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setResponseCode($var)
    {
        GPBUtil::checkInt32($var);
        $this->response_code = $var;

        return $this;
    }

}

