<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: animal_facility.proto

namespace Proto\AnimalFacilityService;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>AnimalFacilityServicePackage.UpdateAnimalFacilityRequest</code>
 */
class UpdateAnimalFacilityRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 animal_id = 1;</code>
     */
    protected $animal_id = 0;
    /**
     * Generated from protobuf field <code>int32 facility_id = 2;</code>
     */
    protected $facility_id = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $animal_id
     *     @type int $facility_id
     * }
     */
    public function __construct($data = NULL) {
        \Proto\Metadata\AnimalFacility::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 animal_id = 1;</code>
     * @return int
     */
    public function getAnimalId()
    {
        return $this->animal_id;
    }

    /**
     * Generated from protobuf field <code>int32 animal_id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setAnimalId($var)
    {
        GPBUtil::checkInt32($var);
        $this->animal_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 facility_id = 2;</code>
     * @return int
     */
    public function getFacilityId()
    {
        return $this->facility_id;
    }

    /**
     * Generated from protobuf field <code>int32 facility_id = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setFacilityId($var)
    {
        GPBUtil::checkInt32($var);
        $this->facility_id = $var;

        return $this;
    }

}

