<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: animal_vaccination.proto

namespace Proto\AnimalVaccinationService;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * AnimalVaccination message
 *
 * Generated from protobuf message <code>AnimalVaccinationServicePackage.AnimalVaccination</code>
 */
class AnimalVaccination extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional int32 id = 1;</code>
     */
    protected $id = null;
    /**
     * Generated from protobuf field <code>int32 animal_id = 2;</code>
     */
    protected $animal_id = 0;
    /**
     * Generated from protobuf field <code>int32 vaccination_id = 3;</code>
     */
    protected $vaccination_id = 0;
    /**
     * Generated from protobuf field <code>optional bool is_done = 4;</code>
     */
    protected $is_done = null;
    /**
     * Generated from protobuf field <code>optional string vaccination_done_on_date = 5;</code>
     */
    protected $vaccination_done_on_date = null;
    /**
     * Generated from protobuf field <code>optional string due_date = 6;</code>
     */
    protected $due_date = null;
    /**
     * Generated from protobuf field <code>optional int32 facility_id = 7;</code>
     */
    protected $facility_id = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $id
     *     @type int $animal_id
     *     @type int $vaccination_id
     *     @type bool $is_done
     *     @type string $vaccination_done_on_date
     *     @type string $due_date
     *     @type int $facility_id
     * }
     */
    public function __construct($data = NULL) {
        \Proto\Metadata\AnimalVaccination::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional int32 id = 1;</code>
     * @return int
     */
    public function getId()
    {
        return isset($this->id) ? $this->id : 0;
    }

    public function hasId()
    {
        return isset($this->id);
    }

    public function clearId()
    {
        unset($this->id);
    }

    /**
     * Generated from protobuf field <code>optional int32 id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt32($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 animal_id = 2;</code>
     * @return int
     */
    public function getAnimalId()
    {
        return $this->animal_id;
    }

    /**
     * Generated from protobuf field <code>int32 animal_id = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setAnimalId($var)
    {
        GPBUtil::checkInt32($var);
        $this->animal_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 vaccination_id = 3;</code>
     * @return int
     */
    public function getVaccinationId()
    {
        return $this->vaccination_id;
    }

    /**
     * Generated from protobuf field <code>int32 vaccination_id = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setVaccinationId($var)
    {
        GPBUtil::checkInt32($var);
        $this->vaccination_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool is_done = 4;</code>
     * @return bool
     */
    public function getIsDone()
    {
        return isset($this->is_done) ? $this->is_done : false;
    }

    public function hasIsDone()
    {
        return isset($this->is_done);
    }

    public function clearIsDone()
    {
        unset($this->is_done);
    }

    /**
     * Generated from protobuf field <code>optional bool is_done = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsDone($var)
    {
        GPBUtil::checkBool($var);
        $this->is_done = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string vaccination_done_on_date = 5;</code>
     * @return string
     */
    public function getVaccinationDoneOnDate()
    {
        return isset($this->vaccination_done_on_date) ? $this->vaccination_done_on_date : '';
    }

    public function hasVaccinationDoneOnDate()
    {
        return isset($this->vaccination_done_on_date);
    }

    public function clearVaccinationDoneOnDate()
    {
        unset($this->vaccination_done_on_date);
    }

    /**
     * Generated from protobuf field <code>optional string vaccination_done_on_date = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setVaccinationDoneOnDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->vaccination_done_on_date = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string due_date = 6;</code>
     * @return string
     */
    public function getDueDate()
    {
        return isset($this->due_date) ? $this->due_date : '';
    }

    public function hasDueDate()
    {
        return isset($this->due_date);
    }

    public function clearDueDate()
    {
        unset($this->due_date);
    }

    /**
     * Generated from protobuf field <code>optional string due_date = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setDueDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->due_date = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int32 facility_id = 7;</code>
     * @return int
     */
    public function getFacilityId()
    {
        return isset($this->facility_id) ? $this->facility_id : 0;
    }

    public function hasFacilityId()
    {
        return isset($this->facility_id);
    }

    public function clearFacilityId()
    {
        unset($this->facility_id);
    }

    /**
     * Generated from protobuf field <code>optional int32 facility_id = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setFacilityId($var)
    {
        GPBUtil::checkInt32($var);
        $this->facility_id = $var;

        return $this;
    }

}

