<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: animal_vaccination.proto

namespace Proto\AnimalVaccinationService;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>AnimalVaccinationServicePackage.CreateAnimalVaccinationResponse</code>
 */
class CreateAnimalVaccinationResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.AnimalVaccinationServicePackage.AnimalVaccination animal_vaccination = 1;</code>
     */
    protected $animal_vaccination = null;
    /**
     * Generated from protobuf field <code>int32 response_code = 2;</code>
     */
    protected $response_code = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Proto\AnimalVaccinationService\AnimalVaccination $animal_vaccination
     *     @type int $response_code
     * }
     */
    public function __construct($data = NULL) {
        \Proto\Metadata\AnimalVaccination::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.AnimalVaccinationServicePackage.AnimalVaccination animal_vaccination = 1;</code>
     * @return \Proto\AnimalVaccinationService\AnimalVaccination|null
     */
    public function getAnimalVaccination()
    {
        return $this->animal_vaccination;
    }

    public function hasAnimalVaccination()
    {
        return isset($this->animal_vaccination);
    }

    public function clearAnimalVaccination()
    {
        unset($this->animal_vaccination);
    }

    /**
     * Generated from protobuf field <code>.AnimalVaccinationServicePackage.AnimalVaccination animal_vaccination = 1;</code>
     * @param \Proto\AnimalVaccinationService\AnimalVaccination $var
     * @return $this
     */
    public function setAnimalVaccination($var)
    {
        GPBUtil::checkMessage($var, \Proto\AnimalVaccinationService\AnimalVaccination::class);
        $this->animal_vaccination = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 response_code = 2;</code>
     * @return int
     */
    public function getResponseCode()
    {
        return $this->response_code;
    }

    /**
     * Generated from protobuf field <code>int32 response_code = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setResponseCode($var)
    {
        GPBUtil::checkInt32($var);
        $this->response_code = $var;

        return $this;
    }

}

