<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: animal_vaccination.proto

namespace Proto\AnimalVaccinationService;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Responses
 *
 * Generated from protobuf message <code>AnimalVaccinationServicePackage.GetAnimalVaccinationsResponse</code>
 */
class GetAnimalVaccinationsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .AnimalVaccinationServicePackage.AnimalVaccination animal_vaccinations = 1;</code>
     */
    private $animal_vaccinations;
    /**
     * Generated from protobuf field <code>int32 response_code = 2;</code>
     */
    protected $response_code = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Proto\AnimalVaccinationService\AnimalVaccination>|\Google\Protobuf\Internal\RepeatedField $animal_vaccinations
     *     @type int $response_code
     * }
     */
    public function __construct($data = NULL) {
        \Proto\Metadata\AnimalVaccination::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .AnimalVaccinationServicePackage.AnimalVaccination animal_vaccinations = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAnimalVaccinations()
    {
        return $this->animal_vaccinations;
    }

    /**
     * Generated from protobuf field <code>repeated .AnimalVaccinationServicePackage.AnimalVaccination animal_vaccinations = 1;</code>
     * @param array<\Proto\AnimalVaccinationService\AnimalVaccination>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAnimalVaccinations($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Proto\AnimalVaccinationService\AnimalVaccination::class);
        $this->animal_vaccinations = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 response_code = 2;</code>
     * @return int
     */
    public function getResponseCode()
    {
        return $this->response_code;
    }

    /**
     * Generated from protobuf field <code>int32 response_code = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setResponseCode($var)
    {
        GPBUtil::checkInt32($var);
        $this->response_code = $var;

        return $this;
    }

}

