<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: animal_screening.proto

namespace Proto\AnimalScreeningService;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * AnimalScreening message
 *
 * Generated from protobuf message <code>AnimalScreeningServicePackage.AnimalScreening</code>
 */
class AnimalScreening extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional int32 id = 1;</code>
     */
    protected $id = null;
    /**
     * Generated from protobuf field <code>int32 animal_id = 2;</code>
     */
    protected $animal_id = 0;
    /**
     * Generated from protobuf field <code>optional string screening_result = 3;</code>
     */
    protected $screening_result = null;
    /**
     * Generated from protobuf field <code>optional string remarks = 4;</code>
     */
    protected $remarks = null;
    /**
     * Generated from protobuf field <code>repeated int32 symptom_id = 5;</code>
     */
    private $symptom_id;
    /**
     * Generated from protobuf field <code>repeated int32 disease_id = 6;</code>
     */
    private $disease_id;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $id
     *     @type int $animal_id
     *     @type string $screening_result
     *     @type string $remarks
     *     @type array<int>|\Google\Protobuf\Internal\RepeatedField $symptom_id
     *     @type array<int>|\Google\Protobuf\Internal\RepeatedField $disease_id
     * }
     */
    public function __construct($data = NULL) {
        \Proto\Metadata\AnimalScreening::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional int32 id = 1;</code>
     * @return int
     */
    public function getId()
    {
        return isset($this->id) ? $this->id : 0;
    }

    public function hasId()
    {
        return isset($this->id);
    }

    public function clearId()
    {
        unset($this->id);
    }

    /**
     * Generated from protobuf field <code>optional int32 id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt32($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 animal_id = 2;</code>
     * @return int
     */
    public function getAnimalId()
    {
        return $this->animal_id;
    }

    /**
     * Generated from protobuf field <code>int32 animal_id = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setAnimalId($var)
    {
        GPBUtil::checkInt32($var);
        $this->animal_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string screening_result = 3;</code>
     * @return string
     */
    public function getScreeningResult()
    {
        return isset($this->screening_result) ? $this->screening_result : '';
    }

    public function hasScreeningResult()
    {
        return isset($this->screening_result);
    }

    public function clearScreeningResult()
    {
        unset($this->screening_result);
    }

    /**
     * Generated from protobuf field <code>optional string screening_result = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setScreeningResult($var)
    {
        GPBUtil::checkString($var, True);
        $this->screening_result = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string remarks = 4;</code>
     * @return string
     */
    public function getRemarks()
    {
        return isset($this->remarks) ? $this->remarks : '';
    }

    public function hasRemarks()
    {
        return isset($this->remarks);
    }

    public function clearRemarks()
    {
        unset($this->remarks);
    }

    /**
     * Generated from protobuf field <code>optional string remarks = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setRemarks($var)
    {
        GPBUtil::checkString($var, True);
        $this->remarks = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated int32 symptom_id = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSymptomId()
    {
        return $this->symptom_id;
    }

    /**
     * Generated from protobuf field <code>repeated int32 symptom_id = 5;</code>
     * @param array<int>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSymptomId($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT32);
        $this->symptom_id = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated int32 disease_id = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDiseaseId()
    {
        return $this->disease_id;
    }

    /**
     * Generated from protobuf field <code>repeated int32 disease_id = 6;</code>
     * @param array<int>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDiseaseId($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT32);
        $this->disease_id = $arr;

        return $this;
    }

}

