<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: animal_screening.proto

namespace Proto\AnimalScreeningService;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>AnimalScreeningServicePackage.CreateAnimalScreeningRequest</code>
 */
class CreateAnimalScreeningRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.AnimalScreeningServicePackage.AnimalScreening animal_screening = 1;</code>
     */
    protected $animal_screening = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Proto\AnimalScreeningService\AnimalScreening $animal_screening
     * }
     */
    public function __construct($data = NULL) {
        \Proto\Metadata\AnimalScreening::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.AnimalScreeningServicePackage.AnimalScreening animal_screening = 1;</code>
     * @return \Proto\AnimalScreeningService\AnimalScreening|null
     */
    public function getAnimalScreening()
    {
        return $this->animal_screening;
    }

    public function hasAnimalScreening()
    {
        return isset($this->animal_screening);
    }

    public function clearAnimalScreening()
    {
        unset($this->animal_screening);
    }

    /**
     * Generated from protobuf field <code>.AnimalScreeningServicePackage.AnimalScreening animal_screening = 1;</code>
     * @param \Proto\AnimalScreeningService\AnimalScreening $var
     * @return $this
     */
    public function setAnimalScreening($var)
    {
        GPBUtil::checkMessage($var, \Proto\AnimalScreeningService\AnimalScreening::class);
        $this->animal_screening = $var;

        return $this;
    }

}

