<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: animal_screening.proto

namespace Proto\AnimalScreeningService;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Responses
 *
 * Generated from protobuf message <code>AnimalScreeningServicePackage.GetAnimalScreeningsResponse</code>
 */
class GetAnimalScreeningsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .AnimalScreeningServicePackage.AnimalScreening animal_screenings = 1;</code>
     */
    private $animal_screenings;
    /**
     * Generated from protobuf field <code>int32 response_code = 2;</code>
     */
    protected $response_code = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Proto\AnimalScreeningService\AnimalScreening>|\Google\Protobuf\Internal\RepeatedField $animal_screenings
     *     @type int $response_code
     * }
     */
    public function __construct($data = NULL) {
        \Proto\Metadata\AnimalScreening::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .AnimalScreeningServicePackage.AnimalScreening animal_screenings = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAnimalScreenings()
    {
        return $this->animal_screenings;
    }

    /**
     * Generated from protobuf field <code>repeated .AnimalScreeningServicePackage.AnimalScreening animal_screenings = 1;</code>
     * @param array<\Proto\AnimalScreeningService\AnimalScreening>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAnimalScreenings($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Proto\AnimalScreeningService\AnimalScreening::class);
        $this->animal_screenings = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 response_code = 2;</code>
     * @return int
     */
    public function getResponseCode()
    {
        return $this->response_code;
    }

    /**
     * Generated from protobuf field <code>int32 response_code = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setResponseCode($var)
    {
        GPBUtil::checkInt32($var);
        $this->response_code = $var;

        return $this;
    }

}

