<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: animal_postmortem.proto

namespace Proto\Metadata;

class AnimalPostmortem
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
©	
animal_postmortem.protoAnimalPostmortemPackage"0
GetAnimalPostmortemsRequest
	animal_id ("m
CreateAnimalPostmortemRequestL
animal_postmortem (21.AnimalPostmortemPackage.TemplateAnimalPostmortem"É
GetAnimalPostmortemsResponseL
animal_postmortem (21.AnimalPostmortemPackage.TemplateAnimalPostmortem
response_code ("Ö
CreateAnimalPostmortemResponseL
animal_postmortem (21.AnimalPostmortemPackage.TemplateAnimalPostmortem
response_code ("…
TemplateAnimalPostmortem
date_of_post_mortem (	
no_of_animals_screened (&
no_of_animals_organs_collected (H
details (27.AnimalPostmortemPackage.TemplateAnimalPostmortemDetail"ê
TemplateAnimalPostmortemDetail
	animal_id (
examined_organ (	
observation (	
carcass_condemnation (	
comments (	2´
AnimalPostmortemServiceÉ
GetAnimalPostmortems4.AnimalPostmortemPackage.GetAnimalPostmortemsRequest5.AnimalPostmortemPackage.GetAnimalPostmortemsResponseâ
CreateAnimalPostmortem6.AnimalPostmortemPackage.CreateAnimalPostmortemRequest7.AnimalPostmortemPackage.CreateAnimalPostmortemResponseB1 Proto\\AnimalPostmortemService‚Proto\\Metadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

