<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: boiler.proto

namespace Proto\Metadata;

class Boiler
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xE5\x01\x0A\x0Cboiler.proto\x12\x14BoilerServicePackage\"\x0D\x0A\x0BPingRequest\"\x1F\x0A\x0CPingResponse\x12\x0F\x0A\x07message\x18\x01 \x01(\x092^\x0A\x0DBoilerService\x12M\x0A\x04Ping\x12!.BoilerServicePackage.PingRequest\x1A\".BoilerServicePackage.PingResponseB'\xCA\x02\x13Proto\\BoilerService\xE2\x02\x0EProto\\Metadatab\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

