<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: iam.proto

namespace Proto\Metadata;

class Iam
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\x9E\x05\x0A\x09iam.proto\x12\x11IamServicePackage\"\x1C\x0A\x0EGetUserRequest\x12\x0A\x0A\x02id\x18\x01 \x01(\x05\"g\x0A\x10UserLoginRequest\x12\x0D\x0A\x05email\x18\x01 \x01(\x09\x12\x10\x0A\x08password\x18\x02 \x01(\x09\x12\x1D\x0A\x10confirm_password\x18\x03 \x01(\x09H\x00\x88\x01\x01B\x13\x0A\x11_confirm_password\"\xA6\x01\x0A\x11UserLoginResponse\x12\x19\x0A\x0Caccess_token\x18\x01 \x01(\x09H\x00\x88\x01\x01\x12\x17\x0A\x0Atoken_type\x18\x02 \x01(\x09H\x01\x88\x01\x01\x12\x17\x0A\x0Aexpires_in\x18\x03 \x01(\x05H\x02\x88\x01\x01\x12\x15\x0A\x0Dresponse_code\x18\x04 \x01(\x05B\x0F\x0A\x0D_access_tokenB\x0D\x0A\x0B_token_typeB\x0D\x0A\x0B_expires_in\"g\x0A\x0FGetUserResponse\x12\x0C\x0A\x04name\x18\x01 \x01(\x09\x12\x10\x0A\x08username\x18\x02 \x01(\x09\x12\x0D\x0A\x05email\x18\x03 \x01(\x09\x12\x0E\x0A\x06mobile\x18\x04 \x01(\x09\x12\x15\x0A\x0Dresponse_code\x18\x05 \x01(\x052\xB6\x01\x0A\x0AIamService\x12P\x0A\x07GetUser\x12!.IamServicePackage.GetUserRequest\x1A\".IamServicePackage.GetUserResponse\x12V\x0A\x09LoginUser\x12#.IamServicePackage.UserLoginRequest\x1A\$.IamServicePackage.UserLoginResponseB\$\xCA\x02\x10Proto\\IamService\xE2\x02\x0EProto\\Metadatab\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

