<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: registry.proto

namespace Proto\Metadata;

class Registry
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xC4\x0A\x0A\x0Eregistry.proto\x12\x16RegistryServicePackage\")\x0A\x1BGetServiceInRegistryRequest\x12\x0A\x0A\x02id\x18\x01 \x01(\x05\".\x0A\x1ECreateServiceInRegistryRequest\x12\x0C\x0A\x04name\x18\x01 \x01(\x09\":\x0A\x1EUpdateServiceInRegistryRequest\x12\x0A\x0A\x02id\x18\x01 \x01(\x09\x12\x0C\x0A\x04name\x18\x02 \x01(\x09\",\x0A\x1EDeleteServiceInRegistryRequest\x12\x0A\x0A\x02id\x18\x01 \x01(\x05\"w\x0A\x1CGetServiceInRegistryResponse\x12@\x0A\x07service\x18\x01 \x01(\x0B2/.RegistryServicePackage.TemplateServiceResponse\x12\x15\x0A\x0Dresponse_code\x18\x02 \x01(\x05\"z\x0A\x1FCreateServiceInRegistryResponse\x12@\x0A\x07service\x18\x01 \x01(\x0B2/.RegistryServicePackage.TemplateServiceResponse\x12\x15\x0A\x0Dresponse_code\x18\x02 \x01(\x05\"z\x0A\x1FUpdateServiceInRegistryResponse\x12@\x0A\x07service\x18\x01 \x01(\x0B2/.RegistryServicePackage.TemplateServiceResponse\x12\x15\x0A\x0Dresponse_code\x18\x02 \x01(\x05\"I\x0A\x1FDeleteServiceInRegistryResponse\x12\x0F\x0A\x07message\x18\x01 \x01(\x09\x12\x15\x0A\x0Dresponse_code\x18\x02 \x01(\x05\"P\x0A\x17TemplateServiceResponse\x12\x0A\x0A\x02id\x18\x01 \x01(\x05\x12\x0C\x0A\x04name\x18\x02 \x01(\x09\x12\x0E\x0A\x06prefix\x18\x03 \x01(\x09\x12\x0B\x0A\x03key\x18\x04 \x01(\x092\x93\x04\x0A\x0FRegistryService\x12w\x0A\x0AGetService\x123.RegistryServicePackage.GetServiceInRegistryRequest\x1A4.RegistryServicePackage.GetServiceInRegistryResponse\x12\x80\x01\x0A\x0DCreateService\x126.RegistryServicePackage.CreateServiceInRegistryRequest\x1A7.RegistryServicePackage.CreateServiceInRegistryResponse\x12\x80\x01\x0A\x0DUpdateService\x126.RegistryServicePackage.UpdateServiceInRegistryRequest\x1A7.RegistryServicePackage.UpdateServiceInRegistryResponse\x12\x80\x01\x0A\x0DDeleteService\x126.RegistryServicePackage.DeleteServiceInRegistryRequest\x1A7.RegistryServicePackage.DeleteServiceInRegistryResponseB)\xCA\x02\x15Proto\\RegistryService\xE2\x02\x0EProto\\Metadatab\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

