<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: species.proto

namespace Proto\SpeciesService;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Responses
 *
 * Generated from protobuf message <code>SpeciesServicePackage.GetSpeciesResponse</code>
 */
class GetSpeciesResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .SpeciesServicePackage.TemplateSpecies species = 1;</code>
     */
    private $species;
    /**
     * Generated from protobuf field <code>int32 response_code = 2;</code>
     */
    protected $response_code = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Proto\SpeciesService\TemplateSpecies>|\Google\Protobuf\Internal\RepeatedField $species
     *     @type int $response_code
     * }
     */
    public function __construct($data = NULL) {
        \Proto\Metadata\Species::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .SpeciesServicePackage.TemplateSpecies species = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSpecies()
    {
        return $this->species;
    }

    /**
     * Generated from protobuf field <code>repeated .SpeciesServicePackage.TemplateSpecies species = 1;</code>
     * @param array<\Proto\SpeciesService\TemplateSpecies>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSpecies($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Proto\SpeciesService\TemplateSpecies::class);
        $this->species = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 response_code = 2;</code>
     * @return int
     */
    public function getResponseCode()
    {
        return $this->response_code;
    }

    /**
     * Generated from protobuf field <code>int32 response_code = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setResponseCode($var)
    {
        GPBUtil::checkInt32($var);
        $this->response_code = $var;

        return $this;
    }

}

