<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: species.proto

namespace Proto\SpeciesService;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Requests
 *
 * Generated from protobuf message <code>SpeciesServicePackage.GetSpeciesRequest</code>
 */
class GetSpeciesRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .SpeciesServicePackage.Filter filter = 1;</code>
     */
    private $filter;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Proto\SpeciesService\Filter>|\Google\Protobuf\Internal\RepeatedField $filter
     * }
     */
    public function __construct($data = NULL) {
        \Proto\Metadata\Species::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .SpeciesServicePackage.Filter filter = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFilter()
    {
        return $this->filter;
    }

    /**
     * Generated from protobuf field <code>repeated .SpeciesServicePackage.Filter filter = 1;</code>
     * @param array<\Proto\SpeciesService\Filter>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFilter($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Proto\SpeciesService\Filter::class);
        $this->filter = $arr;

        return $this;
    }

}

