<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: species.proto

namespace Proto\SpeciesService;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>SpeciesServicePackage.UpdateSpeciesRequest</code>
 */
class UpdateSpeciesRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.SpeciesServicePackage.TemplateSpecies species = 1;</code>
     */
    protected $species = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Proto\SpeciesService\TemplateSpecies $species
     * }
     */
    public function __construct($data = NULL) {
        \Proto\Metadata\Species::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.SpeciesServicePackage.TemplateSpecies species = 1;</code>
     * @return \Proto\SpeciesService\TemplateSpecies|null
     */
    public function getSpecies()
    {
        return $this->species;
    }

    public function hasSpecies()
    {
        return isset($this->species);
    }

    public function clearSpecies()
    {
        unset($this->species);
    }

    /**
     * Generated from protobuf field <code>.SpeciesServicePackage.TemplateSpecies species = 1;</code>
     * @param \Proto\SpeciesService\TemplateSpecies $var
     * @return $this
     */
    public function setSpecies($var)
    {
        GPBUtil::checkMessage($var, \Proto\SpeciesService\TemplateSpecies::class);
        $this->species = $var;

        return $this;
    }

}

