<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rbac.proto

namespace Proto\RbacService;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>RbacServicePackage.CreateRoleUserResponse</code>
 */
class CreateRoleUserResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Generated from protobuf field <code>.RbacServicePackage.TemplateRoleResponse role = 2;</code>
     */
    protected $role = null;
    /**
     * Generated from protobuf field <code>.RbacServicePackage.TemplateUserResponse user = 3;</code>
     */
    protected $user = null;
    /**
     * Generated from protobuf field <code>int32 response_code = 4;</code>
     */
    protected $response_code = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $id
     *     @type \Proto\RbacService\TemplateRoleResponse $role
     *     @type \Proto\RbacService\TemplateUserResponse $user
     *     @type int $response_code
     * }
     */
    public function __construct($data = NULL) {
        \Proto\Metadata\Rbac::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt32($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.RbacServicePackage.TemplateRoleResponse role = 2;</code>
     * @return \Proto\RbacService\TemplateRoleResponse|null
     */
    public function getRole()
    {
        return $this->role;
    }

    public function hasRole()
    {
        return isset($this->role);
    }

    public function clearRole()
    {
        unset($this->role);
    }

    /**
     * Generated from protobuf field <code>.RbacServicePackage.TemplateRoleResponse role = 2;</code>
     * @param \Proto\RbacService\TemplateRoleResponse $var
     * @return $this
     */
    public function setRole($var)
    {
        GPBUtil::checkMessage($var, \Proto\RbacService\TemplateRoleResponse::class);
        $this->role = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.RbacServicePackage.TemplateUserResponse user = 3;</code>
     * @return \Proto\RbacService\TemplateUserResponse|null
     */
    public function getUser()
    {
        return $this->user;
    }

    public function hasUser()
    {
        return isset($this->user);
    }

    public function clearUser()
    {
        unset($this->user);
    }

    /**
     * Generated from protobuf field <code>.RbacServicePackage.TemplateUserResponse user = 3;</code>
     * @param \Proto\RbacService\TemplateUserResponse $var
     * @return $this
     */
    public function setUser($var)
    {
        GPBUtil::checkMessage($var, \Proto\RbacService\TemplateUserResponse::class);
        $this->user = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 response_code = 4;</code>
     * @return int
     */
    public function getResponseCode()
    {
        return $this->response_code;
    }

    /**
     * Generated from protobuf field <code>int32 response_code = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setResponseCode($var)
    {
        GPBUtil::checkInt32($var);
        $this->response_code = $var;

        return $this;
    }

}

