<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rbac.proto

namespace Proto\RbacService;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>RbacServicePackage.UpdateRolePermissionRequest</code>
 */
class UpdateRolePermissionRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Generated from protobuf field <code>int32 role_id = 2;</code>
     */
    protected $role_id = 0;
    /**
     * Generated from protobuf field <code>int32 permission_id = 3;</code>
     */
    protected $permission_id = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $id
     *     @type int $role_id
     *     @type int $permission_id
     * }
     */
    public function __construct($data = NULL) {
        \Proto\Metadata\Rbac::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt32($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 role_id = 2;</code>
     * @return int
     */
    public function getRoleId()
    {
        return $this->role_id;
    }

    /**
     * Generated from protobuf field <code>int32 role_id = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setRoleId($var)
    {
        GPBUtil::checkInt32($var);
        $this->role_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 permission_id = 3;</code>
     * @return int
     */
    public function getPermissionId()
    {
        return $this->permission_id;
    }

    /**
     * Generated from protobuf field <code>int32 permission_id = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setPermissionId($var)
    {
        GPBUtil::checkInt32($var);
        $this->permission_id = $var;

        return $this;
    }

}

