syntax ="proto3";

option php_namespace = "Proto\\AnimalVaccinationService";
option php_metadata_namespace = "Proto\\Metadata";

package AnimalVaccinationServicePackage;
service AnimalVaccinationService {
  rpc GetAnimalVaccinations (GetAnimalVaccinationsRequest) returns (GetAnimalVaccinationsResponse);
  rpc CreateAnimalVaccination (CreateAnimalVaccinationRequest) returns (CreateAnimalVaccinationResponse);
  rpc UpdateAnimalVaccination (UpdateAnimalVaccinationRequest) returns (UpdateAnimalVaccinationResponse);
  rpc DeleteAnimalVaccination (DeleteAnimalVaccinationRequest) returns (DeleteAnimalVaccinationResponse);
}
// Requests
message GetAnimalVaccinationsRequest {
   int32 animal_id= 1;
}
message CreateAnimalVaccinationRequest {
   TemplateAnimalVaccination animal_vaccination = 1;
}
message UpdateAnimalVaccinationRequest {
   TemplateAnimalVaccination animal_vaccination = 1;
}
message DeleteAnimalVaccinationRequest {
    int32 id = 1;
}
// Responses
message GetAnimalVaccinationsResponse {
   repeated TemplateAnimalVaccination animal_vaccinations = 1;
   int32 response_code = 2;
}
message CreateAnimalVaccinationResponse {
   TemplateAnimalVaccination animal_vaccination = 1;
   int32 response_code = 2;
}
message UpdateAnimalVaccinationResponse {
   TemplateAnimalVaccination animal_vaccination = 1;
   int32 response_code = 2;
}
message DeleteAnimalVaccinationResponse {
   bool success = 1;
   int32 response_code = 2;
}
// AnimalVaccination message
message TemplateAnimalVaccination {
   optional int32 id = 1;
   int32 animal_id = 2;
   int32 vaccination_id = 3;
   optional bool is_done = 4;
   optional string vaccination_date = 5;
   optional string due_date = 6;
   optional int32 facility_id = 7;
}