<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: breed.proto

namespace Proto\BreedService;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>BreedServicePackage.GetBreedResponse</code>
 */
class GetBreedResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.BreedServicePackage.TemplateBreed breed = 1;</code>
     */
    protected $breed = null;
    /**
     * Generated from protobuf field <code>int32 response_code = 2;</code>
     */
    protected $response_code = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Proto\BreedService\TemplateBreed $breed
     *     @type int $response_code
     * }
     */
    public function __construct($data = NULL) {
        \Proto\Metadata\Breed::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.BreedServicePackage.TemplateBreed breed = 1;</code>
     * @return \Proto\BreedService\TemplateBreed|null
     */
    public function getBreed()
    {
        return $this->breed;
    }

    public function hasBreed()
    {
        return isset($this->breed);
    }

    public function clearBreed()
    {
        unset($this->breed);
    }

    /**
     * Generated from protobuf field <code>.BreedServicePackage.TemplateBreed breed = 1;</code>
     * @param \Proto\BreedService\TemplateBreed $var
     * @return $this
     */
    public function setBreed($var)
    {
        GPBUtil::checkMessage($var, \Proto\BreedService\TemplateBreed::class);
        $this->breed = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 response_code = 2;</code>
     * @return int
     */
    public function getResponseCode()
    {
        return $this->response_code;
    }

    /**
     * Generated from protobuf field <code>int32 response_code = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setResponseCode($var)
    {
        GPBUtil::checkInt32($var);
        $this->response_code = $var;

        return $this;
    }

}

