<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: breed.proto

namespace Proto\BreedService;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>BreedServicePackage.TemplateSpecies</code>
 */
class TemplateSpecies extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional int32 id = 1;</code>
     */
    protected $id = null;
    /**
     * Generated from protobuf field <code>string name = 2;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>optional string scientific_name = 3;</code>
     */
    protected $scientific_name = null;
    /**
     * Generated from protobuf field <code>optional string description = 4;</code>
     */
    protected $description = null;
    /**
     * Generated from protobuf field <code>bool status = 5;</code>
     */
    protected $status = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $id
     *     @type string $name
     *     @type string $scientific_name
     *     @type string $description
     *     @type bool $status
     * }
     */
    public function __construct($data = NULL) {
        \Proto\Metadata\Breed::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional int32 id = 1;</code>
     * @return int
     */
    public function getId()
    {
        return isset($this->id) ? $this->id : 0;
    }

    public function hasId()
    {
        return isset($this->id);
    }

    public function clearId()
    {
        unset($this->id);
    }

    /**
     * Generated from protobuf field <code>optional int32 id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt32($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string scientific_name = 3;</code>
     * @return string
     */
    public function getScientificName()
    {
        return isset($this->scientific_name) ? $this->scientific_name : '';
    }

    public function hasScientificName()
    {
        return isset($this->scientific_name);
    }

    public function clearScientificName()
    {
        unset($this->scientific_name);
    }

    /**
     * Generated from protobuf field <code>optional string scientific_name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setScientificName($var)
    {
        GPBUtil::checkString($var, True);
        $this->scientific_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string description = 4;</code>
     * @return string
     */
    public function getDescription()
    {
        return isset($this->description) ? $this->description : '';
    }

    public function hasDescription()
    {
        return isset($this->description);
    }

    public function clearDescription()
    {
        unset($this->description);
    }

    /**
     * Generated from protobuf field <code>optional string description = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool status = 5;</code>
     * @return bool
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>bool status = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkBool($var);
        $this->status = $var;

        return $this;
    }

}

