<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: breed.proto

namespace Proto\BreedService;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Breed message
 *
 * Generated from protobuf message <code>BreedServicePackage.TemplateBreed</code>
 */
class TemplateBreed extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional int32 id = 1;</code>
     */
    protected $id = null;
    /**
     * Generated from protobuf field <code>int32 species_id = 2;</code>
     */
    protected $species_id = 0;
    /**
     * Generated from protobuf field <code>string name = 3;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>optional int32 lifespan = 4;</code>
     */
    protected $lifespan = null;
    /**
     * Generated from protobuf field <code>optional string description = 5;</code>
     */
    protected $description = null;
    /**
     * Generated from protobuf field <code>bool can_create_batch = 6;</code>
     */
    protected $can_create_batch = false;
    /**
     * Generated from protobuf field <code>bool status = 7;</code>
     */
    protected $status = false;
    /**
     * Generated from protobuf field <code>optional .BreedServicePackage.TemplateSpecies species = 8;</code>
     */
    protected $species = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $id
     *     @type int $species_id
     *     @type string $name
     *     @type int $lifespan
     *     @type string $description
     *     @type bool $can_create_batch
     *     @type bool $status
     *     @type \Proto\BreedService\TemplateSpecies $species
     * }
     */
    public function __construct($data = NULL) {
        \Proto\Metadata\Breed::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional int32 id = 1;</code>
     * @return int
     */
    public function getId()
    {
        return isset($this->id) ? $this->id : 0;
    }

    public function hasId()
    {
        return isset($this->id);
    }

    public function clearId()
    {
        unset($this->id);
    }

    /**
     * Generated from protobuf field <code>optional int32 id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt32($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 species_id = 2;</code>
     * @return int
     */
    public function getSpeciesId()
    {
        return $this->species_id;
    }

    /**
     * Generated from protobuf field <code>int32 species_id = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setSpeciesId($var)
    {
        GPBUtil::checkInt32($var);
        $this->species_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 3;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int32 lifespan = 4;</code>
     * @return int
     */
    public function getLifespan()
    {
        return isset($this->lifespan) ? $this->lifespan : 0;
    }

    public function hasLifespan()
    {
        return isset($this->lifespan);
    }

    public function clearLifespan()
    {
        unset($this->lifespan);
    }

    /**
     * Generated from protobuf field <code>optional int32 lifespan = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setLifespan($var)
    {
        GPBUtil::checkInt32($var);
        $this->lifespan = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string description = 5;</code>
     * @return string
     */
    public function getDescription()
    {
        return isset($this->description) ? $this->description : '';
    }

    public function hasDescription()
    {
        return isset($this->description);
    }

    public function clearDescription()
    {
        unset($this->description);
    }

    /**
     * Generated from protobuf field <code>optional string description = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool can_create_batch = 6;</code>
     * @return bool
     */
    public function getCanCreateBatch()
    {
        return $this->can_create_batch;
    }

    /**
     * Generated from protobuf field <code>bool can_create_batch = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setCanCreateBatch($var)
    {
        GPBUtil::checkBool($var);
        $this->can_create_batch = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool status = 7;</code>
     * @return bool
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>bool status = 7;</code>
     * @param bool $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkBool($var);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .BreedServicePackage.TemplateSpecies species = 8;</code>
     * @return \Proto\BreedService\TemplateSpecies|null
     */
    public function getSpecies()
    {
        return $this->species;
    }

    public function hasSpecies()
    {
        return isset($this->species);
    }

    public function clearSpecies()
    {
        unset($this->species);
    }

    /**
     * Generated from protobuf field <code>optional .BreedServicePackage.TemplateSpecies species = 8;</code>
     * @param \Proto\BreedService\TemplateSpecies $var
     * @return $this
     */
    public function setSpecies($var)
    {
        GPBUtil::checkMessage($var, \Proto\BreedService\TemplateSpecies::class);
        $this->species = $var;

        return $this;
    }

}

