<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: breed.proto

namespace Proto\BreedService;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>BreedServicePackage.UpdateBreedRequest</code>
 */
class UpdateBreedRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.BreedServicePackage.TemplateBreed breed = 2;</code>
     */
    protected $breed = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Proto\BreedService\TemplateBreed $breed
     * }
     */
    public function __construct($data = NULL) {
        \Proto\Metadata\Breed::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.BreedServicePackage.TemplateBreed breed = 2;</code>
     * @return \Proto\BreedService\TemplateBreed|null
     */
    public function getBreed()
    {
        return $this->breed;
    }

    public function hasBreed()
    {
        return isset($this->breed);
    }

    public function clearBreed()
    {
        unset($this->breed);
    }

    /**
     * Generated from protobuf field <code>.BreedServicePackage.TemplateBreed breed = 2;</code>
     * @param \Proto\BreedService\TemplateBreed $var
     * @return $this
     */
    public function setBreed($var)
    {
        GPBUtil::checkMessage($var, \Proto\BreedService\TemplateBreed::class);
        $this->breed = $var;

        return $this;
    }

}

