<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: animal.proto

namespace Proto\AnimalService;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Animal message
 *
 * Generated from protobuf message <code>AnimalServicePackage.Animal</code>
 */
class Animal extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional int32 id = 1;</code>
     */
    protected $id = null;
    /**
     * Generated from protobuf field <code>string name = 2;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>optional int32 species_id = 3;</code>
     */
    protected $species_id = null;
    /**
     * Generated from protobuf field <code>optional string breed = 4;</code>
     */
    protected $breed = null;
    /**
     * Generated from protobuf field <code>optional int32 age = 5;</code>
     */
    protected $age = null;
    /**
     * Generated from protobuf field <code>optional string description = 6;</code>
     */
    protected $description = null;
    /**
     * Generated from protobuf field <code>bool status = 7;</code>
     */
    protected $status = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $id
     *     @type string $name
     *     @type int $species_id
     *     @type string $breed
     *     @type int $age
     *     @type string $description
     *     @type bool $status
     * }
     */
    public function __construct($data = NULL) {
        \Proto\Metadata\Animal::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional int32 id = 1;</code>
     * @return int
     */
    public function getId()
    {
        return isset($this->id) ? $this->id : 0;
    }

    public function hasId()
    {
        return isset($this->id);
    }

    public function clearId()
    {
        unset($this->id);
    }

    /**
     * Generated from protobuf field <code>optional int32 id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt32($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int32 species_id = 3;</code>
     * @return int
     */
    public function getSpeciesId()
    {
        return isset($this->species_id) ? $this->species_id : 0;
    }

    public function hasSpeciesId()
    {
        return isset($this->species_id);
    }

    public function clearSpeciesId()
    {
        unset($this->species_id);
    }

    /**
     * Generated from protobuf field <code>optional int32 species_id = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setSpeciesId($var)
    {
        GPBUtil::checkInt32($var);
        $this->species_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string breed = 4;</code>
     * @return string
     */
    public function getBreed()
    {
        return isset($this->breed) ? $this->breed : '';
    }

    public function hasBreed()
    {
        return isset($this->breed);
    }

    public function clearBreed()
    {
        unset($this->breed);
    }

    /**
     * Generated from protobuf field <code>optional string breed = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setBreed($var)
    {
        GPBUtil::checkString($var, True);
        $this->breed = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int32 age = 5;</code>
     * @return int
     */
    public function getAge()
    {
        return isset($this->age) ? $this->age : 0;
    }

    public function hasAge()
    {
        return isset($this->age);
    }

    public function clearAge()
    {
        unset($this->age);
    }

    /**
     * Generated from protobuf field <code>optional int32 age = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setAge($var)
    {
        GPBUtil::checkInt32($var);
        $this->age = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string description = 6;</code>
     * @return string
     */
    public function getDescription()
    {
        return isset($this->description) ? $this->description : '';
    }

    public function hasDescription()
    {
        return isset($this->description);
    }

    public function clearDescription()
    {
        unset($this->description);
    }

    /**
     * Generated from protobuf field <code>optional string description = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool status = 7;</code>
     * @return bool
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>bool status = 7;</code>
     * @param bool $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkBool($var);
        $this->status = $var;

        return $this;
    }

}

