<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: animal.proto

namespace Proto\AnimalService;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>AnimalServicePackage.CreateAnimalRequest</code>
 */
class CreateAnimalRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.AnimalServicePackage.TemplateAnimal animal = 1;</code>
     */
    protected $animal = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Proto\AnimalService\TemplateAnimal $animal
     * }
     */
    public function __construct($data = NULL) {
        \Proto\Metadata\Animal::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.AnimalServicePackage.TemplateAnimal animal = 1;</code>
     * @return \Proto\AnimalService\TemplateAnimal|null
     */
    public function getAnimal()
    {
        return $this->animal;
    }

    public function hasAnimal()
    {
        return isset($this->animal);
    }

    public function clearAnimal()
    {
        unset($this->animal);
    }

    /**
     * Generated from protobuf field <code>.AnimalServicePackage.TemplateAnimal animal = 1;</code>
     * @param \Proto\AnimalService\TemplateAnimal $var
     * @return $this
     */
    public function setAnimal($var)
    {
        GPBUtil::checkMessage($var, \Proto\AnimalService\TemplateAnimal::class);
        $this->animal = $var;

        return $this;
    }

}

