<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: animal.proto

namespace Proto\AnimalService;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Responses
 *
 * Generated from protobuf message <code>AnimalServicePackage.GetAnimalsResponse</code>
 */
class GetAnimalsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .AnimalServicePackage.TemplateAnimal animals = 1;</code>
     */
    private $animals;
    /**
     * Generated from protobuf field <code>int32 response_code = 2;</code>
     */
    protected $response_code = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Proto\AnimalService\TemplateAnimal>|\Google\Protobuf\Internal\RepeatedField $animals
     *     @type int $response_code
     * }
     */
    public function __construct($data = NULL) {
        \Proto\Metadata\Animal::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .AnimalServicePackage.TemplateAnimal animals = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAnimals()
    {
        return $this->animals;
    }

    /**
     * Generated from protobuf field <code>repeated .AnimalServicePackage.TemplateAnimal animals = 1;</code>
     * @param array<\Proto\AnimalService\TemplateAnimal>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAnimals($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Proto\AnimalService\TemplateAnimal::class);
        $this->animals = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 response_code = 2;</code>
     * @return int
     */
    public function getResponseCode()
    {
        return $this->response_code;
    }

    /**
     * Generated from protobuf field <code>int32 response_code = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setResponseCode($var)
    {
        GPBUtil::checkInt32($var);
        $this->response_code = $var;

        return $this;
    }

}

