<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: animal_postmortem.proto

namespace Proto\AnimalPostmortemService;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>AnimalPostmortemPackage.CreateAnimalPostmortemResponse</code>
 */
class CreateAnimalPostmortemResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.AnimalPostmortemPackage.TemplateAnimalPostmortem animal_postmortem = 1;</code>
     */
    protected $animal_postmortem = null;
    /**
     * Generated from protobuf field <code>int32 response_code = 2;</code>
     */
    protected $response_code = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Proto\AnimalPostmortemService\TemplateAnimalPostmortem $animal_postmortem
     *     @type int $response_code
     * }
     */
    public function __construct($data = NULL) {
        \Proto\Metadata\AnimalPostmortem::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.AnimalPostmortemPackage.TemplateAnimalPostmortem animal_postmortem = 1;</code>
     * @return \Proto\AnimalPostmortemService\TemplateAnimalPostmortem|null
     */
    public function getAnimalPostmortem()
    {
        return $this->animal_postmortem;
    }

    public function hasAnimalPostmortem()
    {
        return isset($this->animal_postmortem);
    }

    public function clearAnimalPostmortem()
    {
        unset($this->animal_postmortem);
    }

    /**
     * Generated from protobuf field <code>.AnimalPostmortemPackage.TemplateAnimalPostmortem animal_postmortem = 1;</code>
     * @param \Proto\AnimalPostmortemService\TemplateAnimalPostmortem $var
     * @return $this
     */
    public function setAnimalPostmortem($var)
    {
        GPBUtil::checkMessage($var, \Proto\AnimalPostmortemService\TemplateAnimalPostmortem::class);
        $this->animal_postmortem = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 response_code = 2;</code>
     * @return int
     */
    public function getResponseCode()
    {
        return $this->response_code;
    }

    /**
     * Generated from protobuf field <code>int32 response_code = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setResponseCode($var)
    {
        GPBUtil::checkInt32($var);
        $this->response_code = $var;

        return $this;
    }

}

