<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: animal_postmortem.proto

namespace Proto\AnimalPostmortemService;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>AnimalPostmortemPackage.GetAnimalPostmortemsResponse</code>
 */
class GetAnimalPostmortemsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .AnimalPostmortemPackage.TemplateAnimalPostmortem animal_postmortem = 1;</code>
     */
    private $animal_postmortem;
    /**
     * Generated from protobuf field <code>int32 response_code = 2;</code>
     */
    protected $response_code = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Proto\AnimalPostmortemService\TemplateAnimalPostmortem>|\Google\Protobuf\Internal\RepeatedField $animal_postmortem
     *     @type int $response_code
     * }
     */
    public function __construct($data = NULL) {
        \Proto\Metadata\AnimalPostmortem::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .AnimalPostmortemPackage.TemplateAnimalPostmortem animal_postmortem = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAnimalPostmortem()
    {
        return $this->animal_postmortem;
    }

    /**
     * Generated from protobuf field <code>repeated .AnimalPostmortemPackage.TemplateAnimalPostmortem animal_postmortem = 1;</code>
     * @param array<\Proto\AnimalPostmortemService\TemplateAnimalPostmortem>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAnimalPostmortem($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Proto\AnimalPostmortemService\TemplateAnimalPostmortem::class);
        $this->animal_postmortem = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 response_code = 2;</code>
     * @return int
     */
    public function getResponseCode()
    {
        return $this->response_code;
    }

    /**
     * Generated from protobuf field <code>int32 response_code = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setResponseCode($var)
    {
        GPBUtil::checkInt32($var);
        $this->response_code = $var;

        return $this;
    }

}

