<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: animal_postmortem.proto

namespace Proto\AnimalPostmortemService;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>AnimalPostmortemPackage.TemplateAnimalPostmortemDetail</code>
 */
class TemplateAnimalPostmortemDetail extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 animal_id = 1;</code>
     */
    protected $animal_id = 0;
    /**
     * Generated from protobuf field <code>string examined_organ = 2;</code>
     */
    protected $examined_organ = '';
    /**
     * Generated from protobuf field <code>string observation = 3;</code>
     */
    protected $observation = '';
    /**
     * Generated from protobuf field <code>string carcass_condemnation = 4;</code>
     */
    protected $carcass_condemnation = '';
    /**
     * Generated from protobuf field <code>string comments = 5;</code>
     */
    protected $comments = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $animal_id
     *     @type string $examined_organ
     *     @type string $observation
     *     @type string $carcass_condemnation
     *     @type string $comments
     * }
     */
    public function __construct($data = NULL) {
        \Proto\Metadata\AnimalPostmortem::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 animal_id = 1;</code>
     * @return int
     */
    public function getAnimalId()
    {
        return $this->animal_id;
    }

    /**
     * Generated from protobuf field <code>int32 animal_id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setAnimalId($var)
    {
        GPBUtil::checkInt32($var);
        $this->animal_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string examined_organ = 2;</code>
     * @return string
     */
    public function getExaminedOrgan()
    {
        return $this->examined_organ;
    }

    /**
     * Generated from protobuf field <code>string examined_organ = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setExaminedOrgan($var)
    {
        GPBUtil::checkString($var, True);
        $this->examined_organ = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string observation = 3;</code>
     * @return string
     */
    public function getObservation()
    {
        return $this->observation;
    }

    /**
     * Generated from protobuf field <code>string observation = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setObservation($var)
    {
        GPBUtil::checkString($var, True);
        $this->observation = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string carcass_condemnation = 4;</code>
     * @return string
     */
    public function getCarcassCondemnation()
    {
        return $this->carcass_condemnation;
    }

    /**
     * Generated from protobuf field <code>string carcass_condemnation = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setCarcassCondemnation($var)
    {
        GPBUtil::checkString($var, True);
        $this->carcass_condemnation = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string comments = 5;</code>
     * @return string
     */
    public function getComments()
    {
        return $this->comments;
    }

    /**
     * Generated from protobuf field <code>string comments = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setComments($var)
    {
        GPBUtil::checkString($var, True);
        $this->comments = $var;

        return $this;
    }

}

