<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: animal_postmortem.proto

namespace Proto\AnimalPostmortemService;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * animal postmortem message
 *
 * Generated from protobuf message <code>AnimalPostmortemPackage.TemplateAnimalPostmortem</code>
 */
class TemplateAnimalPostmortem extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string date_of_post_mortem = 3;</code>
     */
    protected $date_of_post_mortem = '';
    /**
     * Generated from protobuf field <code>int32 no_of_animals_screened = 4;</code>
     */
    protected $no_of_animals_screened = 0;
    /**
     * Generated from protobuf field <code>int32 no_of_animals_organs_collected = 5;</code>
     */
    protected $no_of_animals_organs_collected = 0;
    /**
     * Generated from protobuf field <code>repeated .AnimalPostmortemPackage.TemplateAnimalPostmortemDetail details = 1;</code>
     */
    private $details;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $date_of_post_mortem
     *     @type int $no_of_animals_screened
     *     @type int $no_of_animals_organs_collected
     *     @type array<\Proto\AnimalPostmortemService\TemplateAnimalPostmortemDetail>|\Google\Protobuf\Internal\RepeatedField $details
     * }
     */
    public function __construct($data = NULL) {
        \Proto\Metadata\AnimalPostmortem::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string date_of_post_mortem = 3;</code>
     * @return string
     */
    public function getDateOfPostMortem()
    {
        return $this->date_of_post_mortem;
    }

    /**
     * Generated from protobuf field <code>string date_of_post_mortem = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setDateOfPostMortem($var)
    {
        GPBUtil::checkString($var, True);
        $this->date_of_post_mortem = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 no_of_animals_screened = 4;</code>
     * @return int
     */
    public function getNoOfAnimalsScreened()
    {
        return $this->no_of_animals_screened;
    }

    /**
     * Generated from protobuf field <code>int32 no_of_animals_screened = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setNoOfAnimalsScreened($var)
    {
        GPBUtil::checkInt32($var);
        $this->no_of_animals_screened = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 no_of_animals_organs_collected = 5;</code>
     * @return int
     */
    public function getNoOfAnimalsOrgansCollected()
    {
        return $this->no_of_animals_organs_collected;
    }

    /**
     * Generated from protobuf field <code>int32 no_of_animals_organs_collected = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setNoOfAnimalsOrgansCollected($var)
    {
        GPBUtil::checkInt32($var);
        $this->no_of_animals_organs_collected = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .AnimalPostmortemPackage.TemplateAnimalPostmortemDetail details = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDetails()
    {
        return $this->details;
    }

    /**
     * Generated from protobuf field <code>repeated .AnimalPostmortemPackage.TemplateAnimalPostmortemDetail details = 1;</code>
     * @param array<\Proto\AnimalPostmortemService\TemplateAnimalPostmortemDetail>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDetails($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Proto\AnimalPostmortemService\TemplateAnimalPostmortemDetail::class);
        $this->details = $arr;

        return $this;
    }

}

