<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: iam.proto

namespace Proto\IamService;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Response Messages ================================================================================================================
 *
 * Generated from protobuf message <code>IamServicePackage.UserLoginResponse</code>
 */
class UserLoginResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional string access_token = 1;</code>
     */
    protected $access_token = null;
    /**
     * Generated from protobuf field <code>optional string token_type = 2;</code>
     */
    protected $token_type = null;
    /**
     * Generated from protobuf field <code>optional int32 expires_in = 3;</code>
     */
    protected $expires_in = null;
    /**
     * Generated from protobuf field <code>int32 response_code = 4;</code>
     */
    protected $response_code = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $access_token
     *     @type string $token_type
     *     @type int $expires_in
     *     @type int $response_code
     * }
     */
    public function __construct($data = NULL) {
        \Proto\Metadata\Iam::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional string access_token = 1;</code>
     * @return string
     */
    public function getAccessToken()
    {
        return isset($this->access_token) ? $this->access_token : '';
    }

    public function hasAccessToken()
    {
        return isset($this->access_token);
    }

    public function clearAccessToken()
    {
        unset($this->access_token);
    }

    /**
     * Generated from protobuf field <code>optional string access_token = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAccessToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->access_token = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string token_type = 2;</code>
     * @return string
     */
    public function getTokenType()
    {
        return isset($this->token_type) ? $this->token_type : '';
    }

    public function hasTokenType()
    {
        return isset($this->token_type);
    }

    public function clearTokenType()
    {
        unset($this->token_type);
    }

    /**
     * Generated from protobuf field <code>optional string token_type = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTokenType($var)
    {
        GPBUtil::checkString($var, True);
        $this->token_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int32 expires_in = 3;</code>
     * @return int
     */
    public function getExpiresIn()
    {
        return isset($this->expires_in) ? $this->expires_in : 0;
    }

    public function hasExpiresIn()
    {
        return isset($this->expires_in);
    }

    public function clearExpiresIn()
    {
        unset($this->expires_in);
    }

    /**
     * Generated from protobuf field <code>optional int32 expires_in = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setExpiresIn($var)
    {
        GPBUtil::checkInt32($var);
        $this->expires_in = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 response_code = 4;</code>
     * @return int
     */
    public function getResponseCode()
    {
        return $this->response_code;
    }

    /**
     * Generated from protobuf field <code>int32 response_code = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setResponseCode($var)
    {
        GPBUtil::checkInt32($var);
        $this->response_code = $var;

        return $this;
    }

}

