<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: identity.proto

namespace Proto\IdentityService;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>IdentityServicePackage.UserLoginRequest</code>
 */
class UserLoginRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string email = 1;</code>
     */
    protected $email = '';
    /**
     * Generated from protobuf field <code>string password = 2;</code>
     */
    protected $password = '';
    /**
     * Generated from protobuf field <code>optional string confirm_password = 3;</code>
     */
    protected $confirm_password = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $email
     *     @type string $password
     *     @type string $confirm_password
     * }
     */
    public function __construct($data = NULL) {
        \Proto\Metadata\Identity::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string email = 1;</code>
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Generated from protobuf field <code>string email = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setEmail($var)
    {
        GPBUtil::checkString($var, True);
        $this->email = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string password = 2;</code>
     * @return string
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     * Generated from protobuf field <code>string password = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPassword($var)
    {
        GPBUtil::checkString($var, True);
        $this->password = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string confirm_password = 3;</code>
     * @return string
     */
    public function getConfirmPassword()
    {
        return isset($this->confirm_password) ? $this->confirm_password : '';
    }

    public function hasConfirmPassword()
    {
        return isset($this->confirm_password);
    }

    public function clearConfirmPassword()
    {
        unset($this->confirm_password);
    }

    /**
     * Generated from protobuf field <code>optional string confirm_password = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setConfirmPassword($var)
    {
        GPBUtil::checkString($var, True);
        $this->confirm_password = $var;

        return $this;
    }

}

