<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: registry.proto

namespace Proto\RegistryService;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Responses;
 *
 * Generated from protobuf message <code>RegistryServicePackage.GetServiceInRegistryResponse</code>
 */
class GetServiceInRegistryResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.RegistryServicePackage.TemplateServiceResponse service = 1;</code>
     */
    protected $service = null;
    /**
     * Generated from protobuf field <code>int32 response_code = 2;</code>
     */
    protected $response_code = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Proto\RegistryService\TemplateServiceResponse $service
     *     @type int $response_code
     * }
     */
    public function __construct($data = NULL) {
        \Proto\Metadata\Registry::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.RegistryServicePackage.TemplateServiceResponse service = 1;</code>
     * @return \Proto\RegistryService\TemplateServiceResponse|null
     */
    public function getService()
    {
        return $this->service;
    }

    public function hasService()
    {
        return isset($this->service);
    }

    public function clearService()
    {
        unset($this->service);
    }

    /**
     * Generated from protobuf field <code>.RegistryServicePackage.TemplateServiceResponse service = 1;</code>
     * @param \Proto\RegistryService\TemplateServiceResponse $var
     * @return $this
     */
    public function setService($var)
    {
        GPBUtil::checkMessage($var, \Proto\RegistryService\TemplateServiceResponse::class);
        $this->service = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 response_code = 2;</code>
     * @return int
     */
    public function getResponseCode()
    {
        return $this->response_code;
    }

    /**
     * Generated from protobuf field <code>int32 response_code = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setResponseCode($var)
    {
        GPBUtil::checkInt32($var);
        $this->response_code = $var;

        return $this;
    }

}

